small fixes Traceback (most recent call last):   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_notebook.py", line 147, in OnPageClose     self[page].OnClose()   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_erlangstc.py", line 643, in OnClose     ErlangSTC.OnClose(self)   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_erlangstc.py", line 604, in OnClose     if self.flyTimer: AttributeError: 'ErlangSTCReadOnly' object has no attribute 'flyTimer' Uncaught exception: Traceback (most recent call last):   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_directoryinfo.py", line 159, in CheckDirectoryChanges     if diff.modifiedFiles: self.FilesModifiedEvent(diff.modifiedFiles)   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_events.py", line 18, in __call__     handler(*args, **kwargs)   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_projectexplorer.py", line 125, in OnFilesModified     self.ProjectFilesModifiedEvent(files)   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_events.py", line 18, in __call__     handler(*args, **kwargs)   File "d:\Projects\NoiseIDE\NoiseIDEPython\idn_erlangstc.py", line 651, in OnProjectFilesModified     if f == self.filePath:   File "c:\Programming\Python27\lib\site-packages\wx-2.9.4-msw\wx\_core.py", line 16721, in __getattr__     raise PyDeadObjectError(self.attrStr % self._name) PyDeadObjectError: The C++ part of the ErlangSTCReadOnly object has been deleted, attribute access no longer allowed.